### ISSUE TITLE
underscore-deep-extend

### ISSUE THREAD

**Issue by loranger** [mrcsmcln/laravel-elixir-images#3]
I've got a fresh laravel and just install laravel-elixir-image but it seems a dependency is missing.

As soon as I launch gulp, here is the error I receive:

```
$ gulp
module.js:474
    throw err;
    ^

Error: Cannot find module 'underscore-deep-extend'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/loranger/Developer/my_project/node_modules/laravel-elixir-images/index.js:9:17)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

**Comment by mrcsmcln** [comment]
This extension only works with `laravel-elixir@5.0.0` right now. I'll update it once 6.0 is out of RC territory.

**Comment by loranger** [comment]
All right, thanks !

By the way: Elixir 6.0 is distributed with Laravel 5.3 and doesn't seems to be a release candidate
